### ISSUE TITLE
Configuration override

### ISSUE THREAD

**Issue by MartinBR95** [ValiValpas/taskopen#115]
I have recently installed taskopen but every time I use it I get:

Configuration override rc.verbose:off
Configuration override rc.json.array:on
Configuration override rc.verbose:off
Configuration override rc.json.array:on

It still works but it is annoying

PD: I haven't modified any configuration

Thanks for your time

**Comment by ValiValpas** [comment]
Hi @MartinBR95 , I released a new version that fixes this.

**Comment by scottkosty** [comment]
@ValiValpas I wonder if we can come up with a more robust fix. I don't think that all of STDERR should be muted. It could be providing important warnings/errors. What do you think about doing something like the following?

    task rc.verbose:blank,label,edit

or (I forget if taskopen depends on any of that information for parsing):

    task rc.verbose:off

**Comment by ValiValpas** [comment]
Thanks @scottkosty I like your first suggestion as it basically does the same as rc.verbose=off without triggering the 'Configuration override' message.

**Comment by scottkosty** [comment]
@ValiValpas thanks, looks good!
