### ISSUE TITLE
Is it possible to use an empty notes regex?

### ISSUE THREAD

**Issue by tterranigma** [ValiValpas/taskopen#117]
I would like to use `taskopen -n` to create a note on the fly without using `task annotate` first. I tried setting `NOTES_REGEX` to `".*"`, `""`, `" "` and others. But I couldn't make it work. Is there a way to achieve this?

**Comment by ValiValpas** [comment]
@tterranigma have you looked at the `NO_ANNOTATION_HOOK`? I think this is what you're looking for.

**Comment by tterranigma** [comment]
Yes, that solved it for me. I totally missed that. Thanks for pointing it out!
