### ISSUE TITLE
include in-line annotations

### ISSUE THREAD

**Issue by linuxcaffe** [ValiValpas/taskopen#24]
Annotations that do not link to external files are still annotations, there is no restrictions on the length of an in-line annotation, they can have labels and they should be treated as first-class citizens. 
In opening such an annotations, your $EDITOR is the only logical choice, but they should be listed with the others, and after

$ task 1 annotate www.taskwarrior.org
$ task 1 annotate I want to consider this
$ task 1 annotate ~/tasknotes/1.txt
$ taskopen 1

the answer should be 

3 annotation(s) found.

Please select an annotation:
   1) www.taskwarrior.org
   2) I want to consider this
   3) ~/tasknotes/1.txt
Type number:

**Comment by ValiValpas** [comment]
This is now configurable by setting TEXT_REGEX in taskopenrc.
