### ISSUE TITLE
RFE: taskopen -T

### ISSUE THREAD

**Issue by linuxcaffe** [ValiValpas/taskopen#37]
-T as in hide Text annotations
(formerly -R as in Regular annotations)
(this is all in active development ;)

(ie. not links or attachments, but "in-line" annotations)

The -t option might cause taskopen to list only regular (non-link) annotations. 
-T would hide any such annotations 

For example, text annotations such as;

    $ task 1 annotate I want to consider this
    $ task 2 annotate idea: consider buying a tiny note-book, that looks like an iPhone.
    $ task 3 annotate km: 193023-193141
    $ task 4 annotate minutes: Consider This meeting \\n 12:12 - welcome \\n 13:52 break for lunch 

related to #24 and #31

**Comment by ValiValpas** [comment]
This is now implemented on the devel branch and will go into the 1.1 release quite soon. There is also a TEXT_REGEX option in taskopenrc that needs to be set (e.g. ".*").

**Comment by linuxcaffe** [comment]
This is good news indeed! I can't wait to try it! Thanks!
