### ISSUE TITLE
is taskopen broken on taskwarrior 2.4.x ?

### ISSUE THREAD

**Issue by linuxcaffe** [ValiValpas/taskopen#88]
I haven't played around with taskopen in a while, and after installing a fresh version of taskwarrior and taskopen on a new laptop, meeting the dependencies and creating the default taskopenrc, taskopen seems to hang strangely, some kind of problem when vim is invoked, it seems.

looks like this;
<pre>
mouse@StPetes:~$ taskopen 
/usr/bin/vim
</pre>
and is just hung, requiring Ctrl-C

This is a near perfect clean install of a current xubuntu (ubuntu vivid) and taskwarrior 2.4.5, and that implies that the problem might be more widespread, and not a result of my goofy custom configurations.

--version and diag output to follow

**Comment by ValiValpas** [comment]
@linuxcaffe: I cannot reproduce this at the moment. Please provide the diag output, i.e. `taskopen -V`.

**Comment by linuxcaffe** [comment]
UPDATE!
taskopen working much better.. with a few tasks having annotations ;-)  
mostly PEBKAC!
but there remains the "/usr/bin/vim" artifact, that I can't explain, but I'll close this erroneous issue, and open another, If I can't locate the pebkac in that one.

Yes, of course, this is on a fresh installed laptop with xubuntu (ubuntu vivid)
<pre>
mouse@StPetes:~$ uname -a ;taskopen -V ; task version
Linux StPetes 3.19.0-18-generic #18-Ubuntu SMP Tue May 19 18:30:59 UTC 2015 i686 i686 i686 GNU/Linux

Taskopen, release v1.0.2, revision 213 (7e391ea)
Copyright 2010-2014, Johannes Schlatow.

/usr/bin/vim
Environment
    Platform:      linux
    Perl:          v5.20.2
    Taskwarrior:   2.4.5 (5713314)
    xdg-open:      xdg-open 1.0.2
    Configuration: /home/mouse/.taskopenrc

Current configuration
  Binaries and paths:
    BROWSER            = xdg-open
    TASKBIN            = task rc.verbose=off rc.json.array=on
    EDITOR             = vim
    XDG                = xdg-open
    PATH               = /usr/share/taskopen/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

  Others:
    NOTES_FOLDER       = $HOME/tasknotes/
    NOTES_EXT          = .txt
    NOTES_FILE         = $HOME/tasknotes/UUID.txt
    NOTES_CMD          = vim "$HOME/tasknotes/UUID.txt"
    DEFAULT_FILTER     = status.is:pending
    DEFAULT_SORT       = 
                current: 
    DEFAULT-i          = ls -la
                current: ls -la
    DEFAULT-x          = $FILE
    DEBUG              = 0
    NOTES_REGEX        = Notes
    BROWSER_REGEX      = www|http
    FILE_REGEX         = \.|\/|~
    CUSTOM1_REGEX      = 
    CUSTOM1_CMD        = 
    CUSTOM2_REGEX      = 
    CUSTOM2_CMD        = 
Use of uninitialized value $NO_ANNOTATION_HOOK in concatenation (.) or string at /usr/bin/taskopen line 431.
    NO_ANNOTATION_HOOK = 
    TASK_ATTRIBUTES    = 


task 2.4.5 built for linux
Copyright (C) 2006 - 2015 P. Beckingham, F. Hernandez.
..snip
</pre>

<pre>
