### ISSUE TITLE
"No annotation found." is misleading. Replace by "No compatible annotation found."

### ISSUE THREAD

**Issue by SNBasti** [ValiValpas/taskopen#90]
Hi. I am trying to add the taskopen feature to taskwarrior.
First I create a task and add a Note with the command: 

```
task add project:Test TestTask
Created task 3. 
task 3 annotate TestNote
```

Running `task info 3` produces the output: 

```
ID Age Project Description  Urg 
 3 34s Test    TestTask [1]  1.8

1 task
sebastian@seb:~/taskopen$ task info 3 

Name          Value                                            
ID            3
Description   TestTask                                         
                2016-03-06 18:03:02 TestNote                   
Status        Pending
Project       Test                                             
Entered       2016-03-06 18:02:52 (1min)
Last modified 2016-03-06 18:03:02 (53s)                        
Virtual tags  ANNOTATED PENDING READY UNBLOCKED LATEST PROJECT
UUID          1f4647b9-57a6-4abb-9ea1-ba2d7ff98573             
Urgency        1.8

    project          1 *    1 =      1
    annotations    0.8 *    1 =    0.8
                                ------
                                   1.8

Date                Modification                   
2016-03-06 18:03:02 Annotation of 'TestNote' added.
```

Running `taskopen 3` produces the output: 
```
/usr/bin/vim
Configuration override rc.verbose:off
Configuration override rc.json.array:on
Configuration override rc.verbose:off
Configuration override rc.json.array:on
No annotation found.
```

**Comment by scottkosty** [comment]
I believe that "No annotation found" means "No annotation found that taskopen knows how to handle". Instead of annotating "TestNote", try instead "http://www.bbc.co.uk". Then when you use taskopen it should open it with your browser.

**Comment by ValiValpas** [comment]
@SNBasti, sorry I missed that you opened this issue. Actually @scottkosty is absolutely right, thanks for filling in for me ;-)

**Comment by linuxcaffe** [comment]
This is related to issue #24, which is, imho, the taskopen showstopper. I
still believe taskopen would have many more uses if existing functionality
could be applied to non-link-type annotations.

**Comment by linuxcaffe** [comment]
..and I apologize for being such a persistent ass about it. ;-)

**Comment by ValiValpas** [comment]
@linuxcaffe  I think I now found a solution by adding a TEXT_REGEX option in taskopenrc and implementing the command line switches -t/-T. However, there is still a partial showstopper on the taskwarrior side (see TW-1821).
