### ISSUE TITLE
tasknote refinements

### ISSUE THREAD

**Issue by linuxcaffe** [ValiValpas/taskopen#95]
Tasknotes (text files connected to a specific task by UUID naming convention) have some strengths and some weaknesses. 

Strengths; they are more flexible than annotations.

Weaknesses;
- long, meaningless names
- no way to see the task description/ details/ status while editing note
- notes are easily orphaned, after task is completed/ deleted

In working last year on another task-related project (https://github.com/blakesweeney/unite-taskwarrior) which also has a tasknotes implementation, we came up with some effective answers;

File naming conventions
- use UUID.short instead of full UUID
- use "tasknote" as part of the name
- allow user-definable filename extension (eg. .txt, .md, .wiki)
so a tasknote might be named "22cacc3b.tasknote.wiki" for example, which is more helpful and less cumbersome than "78f03da4-d08b-482e-ad34-80c92d4f5598.txt" and can be recognized by vim as a filetype to be handled with taskwiki (for example)

And secondly, on creation of a tasknote, unite-taskwarrior prepends the first line with a "* [ ] " and writes the task description, and appends the UUID.short (like #22cacc3b) so the first line of a tasknote includes a description of the task it is related to, and (bonus) it is also taskwiki-compliant, so that from within the tasknote, the task itself can be acted upon in several ways. That first line might look like;

`* [ ] call Gordo about redheads  #02275a77`

(the two spaces between the description, and the "#" are important)

With these changes, tasknotes become more useful, and imho taskopen's implementation of tasknote functionality would benefit from their adoption.

thanks :)

**Comment by ValiValpas** [comment]
@linuxcaffe I like the idea of supporting different file extensions and it turned out to be quite easy to implement. You can find the changes and an example in the taskopenrc.5 manpage on the devel branch (6eebc0a3308ca797e948aa8d26583353551adb42).

**Comment by ValiValpas** [comment]
This is actually released now with v1.1.2.

**Comment by linuxcaffe** [comment]
That's great Johannes, thanks!
I'm delighted to see continued development of taskopen, and I'm gonna file some other tasknotes refinements as separate issues. Go team!
